---
- name: Execute command on multiple servers
  hosts: meminfo
  gather_facts: true

  tasks:
    - name: Run command
      shell: cat /proc/meminfo | egrep 'MemTotal|SUnreclaim'
      register: command_output

    - name: Store output in file
      copy:
        content: "{{ command_output.stdout }}"
        dest: "/tmp/{{ inventory_hostname }}_meminfo.txt"

    - name: Fetch file from remote to local
      fetch:
        src: "/tmp/{{ inventory_hostname }}_meminfo.txt"
        dest: "/home/raj.ayush/Desktop/vscodefile/falcon/"
        flat: yes
